/* Generated By:JJTree: Do not edit this line. ASTDefaultLiteral.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.metadatacenter.jsonss.parser;

public
class ASTDefaultLiteralValueDirective extends SimpleNode {

  public String defaultLiteralValue; /* Manually added */

  public ASTDefaultLiteralValueDirective(int id) {
    super(id);
  }

  public ASTDefaultLiteralValueDirective(JSONSSParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=877a67e4ac6a31ee1ecb8c7cc44f662c (do not edit this line) */
