/* Generated By:JJTree: Do not edit this line. ASTEmptyLiteralValueDirective.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.metadatacenter.jsonss.parser;

import org.metadatacenter.jsonss.core.settings.EmptyLiteralValueDirectiveSetting;

public
class ASTEmptyLiteralValueDirective extends SimpleNode {

  public EmptyLiteralValueDirectiveSetting emptyLiteralValueDirectiveSetting;

  public ASTEmptyLiteralValueDirective(int id) {
    super(id);
  }

  public ASTEmptyLiteralValueDirective(JSONSSParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=82a85ab5d911a18fd2fe0e7defa3698d (do not edit this line) */
