/* Generated By:JJTree: Do not edit this line. ASTJSONString.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.metadatacenter.jsonss.parser;

public
class ASTJSONString extends SimpleNode {

  public String s; // Manually added

  public ASTJSONString(int id) {
    super(id);
  }

  public ASTJSONString(JSONSSParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=01eb455d17ba8c2ecb6cd9e82d3d7ebf (do not edit this line) */
