/* Generated By:JJTree: Do not edit this line. ASTJSONNumber.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.metadatacenter.jsonss.parser;

public
class ASTJSONNumber extends SimpleNode {

  public Number n; // Manyally added

  public ASTJSONNumber(int id) {
    super(id);
  }

  public ASTJSONNumber(JSONSSParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=3602044aebd2a280e1490482ae7d6e65 (do not edit this line) */
