/* Generated By:JJTree: Do not edit this line. ASTJSONBoolean.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.metadatacenter.jsonss.parser;

public
class ASTJSONBoolean extends SimpleNode {

  public boolean b; // Manually added

  public ASTJSONBoolean(int id) {
    super(id);
  }

  public ASTJSONBoolean(JSONSSParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=72f4ddd543839d2ceafe4e0cfad86e5b (do not edit this line) */
