/* Generated By:JJTree: Do not edit this line. ASTSourceSpecification.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.metadatacenter.jsonss.parser;

public
class ASTReferenceQualifiedCellLocationSpecification extends SimpleNode {

  public String sourceSpecification; /* Manually added */
  public String cellLocationSpecification; /* Manually added */
  public String literal; /* Manually added */

public ASTReferenceQualifiedCellLocationSpecification(int id) {
    super(id);
  }

  public ASTReferenceQualifiedCellLocationSpecification(JSONSSParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=488cd25c67bf59588f04b27bf6bb02b3 (do not edit this line) */
