/* Generated By:JJTree: Do not edit this line. ASTRangeReference.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.metadatacenter.jsonss.parser;

import org.metadatacenter.jsonss.core.settings.ReferenceDirectivesSettings;

public
class ASTRangeReference extends SimpleNode {

  public ReferenceDirectivesSettings defaultReferenceDirectivesSettings; /* Manually added */
  public String finishCellLocationSpecification; /* Manually added; start location is a node */

  public ASTRangeReference(int id) {
    super(id);
  }

  public ASTRangeReference(JSONSSParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=8b6e31275ff56d69b3836e0cfa45d869 (do not edit this line) */
