/* Generated By:JJTree: Do not edit this line. ASTShiftSetting.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.metadatacenter.jsonss.parser;

import org.metadatacenter.jsonss.core.settings.ShiftDirectiveSetting;

public
class ASTShiftDirective extends SimpleNode {

  public ShiftDirectiveSetting shiftDirectiveSetting; /* Manually added */

  public ASTShiftDirective(int id) {
    super(id);
  }

  public ASTShiftDirective(JSONSSParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=dd3adc3ec8c7e2212369cb9c1c667fe7 (do not edit this line) */
